PRODUCT_COLUMN = "product"
QUANTITY_COLUMN = "quantity"
REVENUE_COLUMN = "revenue"
UNIT_PRICE_COLUMN = "unit_price"

REQUIRED_RAW_SALES_COLUMNS = [
    PRODUCT_COLUMN,
    QUANTITY_COLUMN,
    REVENUE_COLUMN,
]

REQUIRED_PROCESSED_SALES_COLUMNS = [
    PRODUCT_COLUMN,
    QUANTITY_COLUMN,
    REVENUE_COLUMN,
    UNIT_PRICE_COLUMN,
]